import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "components/material-tailwind-theme-provider";
import ReactQueryClientProviders from "config/ReactQueryClientProvider";
import RecoilClientProvider from "config/RecoilClientProvider";
import MainLayout from "components/layouts/main-layout";
import Auth from "components/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Minibox",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const loggedIn = true;

  return (
    <RecoilClientProvider>
      <ReactQueryClientProviders>
        <ThemeProvider>
          {/* @ts-ignore */}
          <html lang="en">
            <head>
              <link
                rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
                integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
                crossOrigin="anonymous"
                referrerPolicy="no-referrer"
              />
            </head>
            <body className={inter.className}>
              {loggedIn ? <MainLayout>{children}</MainLayout> : <Auth />}
            </body>
          </html>
        </ThemeProvider>
      </ReactQueryClientProviders>
    </RecoilClientProvider>
  );
}
